[package]
name = "imageproc"
version = "0.1.0"
authors = ["Yuheng Chen <yuhengchen@sensetime.com>"]
build = "build.rs"

[dependencies]
num  = "*"
time = "*"
libc  = "*"

[[bin]]
name = "perf-imageproc"
path = "tests/perf.rs"
